package Trabajo_1;

import com.google.api.translate.*;

public class Traductor extends javax.swing.JFrame {

    /**
     * Creates new form Traductor
     */
    public Traductor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EsIn = new javax.swing.JTextField();
        EsIt = new javax.swing.JTextField();
        EsFr = new javax.swing.JTextField();
        InEs = new javax.swing.JTextField();
        InIt = new javax.swing.JTextField();
        InFr = new javax.swing.JTextField();
        ItEs = new javax.swing.JTextField();
        ItIn = new javax.swing.JTextField();
        ItFr = new javax.swing.JTextField();
        FrEs = new javax.swing.JTextField();
        FrIn = new javax.swing.JTextField();
        FrIt = new javax.swing.JTextField();
        EspIng = new javax.swing.JButton();
        EspIta = new javax.swing.JButton();
        EspFra = new javax.swing.JButton();
        IngEsp = new javax.swing.JButton();
        IngIta = new javax.swing.JButton();
        IngFra = new javax.swing.JButton();
        ItaEsp = new javax.swing.JButton();
        ItaIng = new javax.swing.JButton();
        ItaFra = new javax.swing.JButton();
        FraEsp = new javax.swing.JButton();
        FraIng = new javax.swing.JButton();
        FraIta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EsIn.setText("Ingrese texto");

        EsIt.setText("Ingrese texto");
        EsIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsItActionPerformed(evt);
            }
        });

        EsFr.setText("Ingrese texto");

        InEs.setText("Ingrese texto");

        InIt.setText("Ingrese texto");

        InFr.setText("Ingrese texto");

        ItEs.setText("Ingrese texto");

        ItIn.setText("Ingrese texto");

        ItFr.setText("Ingrese texto");

        FrEs.setText("Ingrese texto");

        FrIn.setText("Ingrese texto");

        FrIt.setText("Ingrese texto");

        EspIng.setText("Esp - Ing");
        EspIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspIngActionPerformed(evt);
            }
        });

        EspIta.setText("Esp - Ita");
        EspIta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspItaActionPerformed(evt);
            }
        });

        EspFra.setText("Esp - Fra");
        EspFra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspFraActionPerformed(evt);
            }
        });

        IngEsp.setText("Ing - Esp");

        IngIta.setText("Ing - Ita");

        IngFra.setText("Ing - Fra");
        IngFra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngFraActionPerformed(evt);
            }
        });

        ItaEsp.setText("Ita - Esp");

        ItaIng.setText("Ita - Ing");

        ItaFra.setText("Ita - Fra");
        ItaFra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItaFraActionPerformed(evt);
            }
        });

        FraEsp.setText("Fra - Esp");
        FraEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FraEspActionPerformed(evt);
            }
        });

        FraIng.setText("Fra - Ing");

        FraIta.setText("Fra - Ita");
        FraIta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FraItaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(FrIn)
                    .addComponent(FrEs)
                    .addComponent(ItFr)
                    .addComponent(ItIn)
                    .addComponent(ItEs)
                    .addComponent(InFr)
                    .addComponent(InIt)
                    .addComponent(InEs)
                    .addComponent(EsFr)
                    .addComponent(EsIt)
                    .addComponent(EsIn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(FrIt))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EspIng)
                    .addComponent(EspIta)
                    .addComponent(EspFra)
                    .addComponent(IngEsp)
                    .addComponent(IngIta)
                    .addComponent(IngFra)
                    .addComponent(ItaEsp)
                    .addComponent(ItaIng)
                    .addComponent(ItaFra)
                    .addComponent(FraEsp)
                    .addComponent(FraIng)
                    .addComponent(FraIta))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EsIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EspIng, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EsIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EspIta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(EsFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EspFra, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IngEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IngIta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IngFra, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ItaEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ItaIng, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItaFra, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FrEs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FrIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FrIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FraEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FraIng, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FraIta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EspFraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspFraActionPerformed
        try{
            String TextoOriginal = (String)this.EsFr.getText();
            String TextoTraducido = Translate.translate(TextoOriginal, Language.SPANISH, Language.FRENCH);
            this.EsFr.setText(TextoTraducido);
        }catch (Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_EspFraActionPerformed

    private void IngFraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngFraActionPerformed
        try{
            String TextoOriginal = (String)this.InFr.getText();
            String TextoTraducido = Translate.translate(TextoOriginal, Language.ENGLISH, Language.FRENCH);
            this.InFr.setText(TextoTraducido);
        }catch (Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_IngFraActionPerformed

    private void ItaFraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItaFraActionPerformed
        try{
            String TextoOriginal = (String)this.ItFr.getText();
            String TextoTraducido = Translate.translate(TextoOriginal, Language.ITALIAN, Language.FRENCH);
            this.ItFr.setText(TextoTraducido);
        }catch (Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_ItaFraActionPerformed

    private void FraItaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FraItaActionPerformed
        try{
            String TextoOriginal = (String)this.FrIt.getText();
            String TextoTraducido = Translate.translate(TextoOriginal, Language.FRENCH, Language.ITALIAN);
            this.FrIt.setText(TextoTraducido);
        }catch (Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_FraItaActionPerformed

    private void EspItaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspItaActionPerformed
        try{
            String TextoOriginal = (String)this.EsIt.getText();
            String TextoTraducido = Translate.translate(TextoOriginal, Language.SPANISH, Language.ITALIAN);
            this.EsIt.setText(TextoTraducido);
        }catch (Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_EspItaActionPerformed

    private void FraEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FraEspActionPerformed
        try{
            String TextoOriginal = (String)this.FrEs.getText();
            String TextoTraducido = Translate.translate(TextoOriginal, Language.FRENCH, Language.SPANISH);
            this.FrEs.setText(TextoTraducido);
        }catch (Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_FraEspActionPerformed

    private void EsItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsItActionPerformed
        try{
            String TextoOriginal = (String)this.EsIt.getText();
            String TextoTraducido = Translate.translate(TextoOriginal, Language.SPANISH, Language.ITALIAN);
            this.EsIt.setText(TextoTraducido);
        }catch (Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_EsItActionPerformed

    private void EspIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspIngActionPerformed
        try{
            String TextoOriginal = (String)this.EsIn.getText();
            String TextoTraducido = Translate.translate(TextoOriginal, Language.SPANISH, Language.ENGLISH);
            this.EsIn.setText(TextoTraducido);
        }catch (Exception ex){
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_EspIngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EsFr;
    private javax.swing.JTextField EsIn;
    private javax.swing.JTextField EsIt;
    private javax.swing.JButton EspFra;
    private javax.swing.JButton EspIng;
    private javax.swing.JButton EspIta;
    private javax.swing.JTextField FrEs;
    private javax.swing.JTextField FrIn;
    private javax.swing.JTextField FrIt;
    private javax.swing.JButton FraEsp;
    private javax.swing.JButton FraIng;
    private javax.swing.JButton FraIta;
    private javax.swing.JTextField InEs;
    private javax.swing.JTextField InFr;
    private javax.swing.JTextField InIt;
    private javax.swing.JButton IngEsp;
    private javax.swing.JButton IngFra;
    private javax.swing.JButton IngIta;
    private javax.swing.JTextField ItEs;
    private javax.swing.JTextField ItFr;
    private javax.swing.JTextField ItIn;
    private javax.swing.JButton ItaEsp;
    private javax.swing.JButton ItaFra;
    private javax.swing.JButton ItaIng;
    // End of variables declaration//GEN-END:variables
}
